#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean TCAT
# wclean tcat-1p-inc-steady
# wclean tcat-1p-inc-transient
wclean tcat-1p-steady
# wclean tcat-1p-transient

# ----------------------------------------------------------------- end-of-file
